# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Builder stage
FROM node:lts-alpine AS builder
WORKDIR /app

# Install dependencies and build
COPY package.json package-lock.json tsconfig.json ./
RUN npm ci

COPY src ./src
RUN npm run build && npm prune --production

# Final stage
FROM node:lts-alpine
WORKDIR /app

# Copy built artifacts and production deps
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/node_modules ./node_modules
COPY package.json ./

ENV NODE_ENV production

# Use node to run the MCP server
ENTRYPOINT ["node", "dist/index.js"]
