# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# syntax=docker/dockerfile:1

# Stage 1: build
FROM node:lts-alpine AS builder
WORKDIR /app
# Install build tools (including devDependencies)
COPY package.json package-lock.json tsconfig.json ./
RUN npm install
# Copy sources and build
COPY src ./src
RUN npm run build

# Stage 2: production image
FROM node:lts-alpine
WORKDIR /app
ENV NODE_ENV=production
# Install only runtime dependencies
COPY package.json package-lock.json ./
RUN npm install --omit=dev
# Copy built artifacts
COPY --from=builder /app/dist ./dist
# Use stdio transport, no ports to expose
ENTRYPOINT ["node", "dist/index.js"]
